name: Sync Types

on:
  # schedule:
  #   - cron: "0 0 * * 5"
  #   - cron: "42 0 * * *"
  push: # for testing
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-


      - name: install
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false

      - name: execute sync script
        run: |
          pnpm install ts-node -g
          pnpm run build:types
          pnpm run build:json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "refactor(types): build types"
          title: "refactor(types): build types"
          body: "build types"
